package com.arloor.emarket.domain;

public class CartKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.uname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.pid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.uname
     *
     * @return the value of cart.uname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.uname
     *
     * @param uname the value for cart.uname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.pid
     *
     * @return the value of cart.pid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.pid
     *
     * @param pid the value for cart.pid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}