package com.arloor.emarket.domain;

public class Cart extends CartKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.num
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.num
     *
     * @return the value of cart.num
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.num
     *
     * @param num the value for cart.num
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}