package com.arloor.emarket.domain;

public class ConsigneeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.uname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.addr
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.uname
     *
     * @return the value of consignee.uname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.uname
     *
     * @param uname the value for consignee.uname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.addr
     *
     * @return the value of consignee.addr
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.addr
     *
     * @param addr the value for consignee.addr
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }
}