package com.arloor.emarket.domain;

public class Consignee extends ConsigneeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.consignee
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.tel
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.zipcode
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee.default
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Boolean default;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.consignee
     *
     * @return the value of consignee.consignee
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.consignee
     *
     * @param consignee the value for consignee.consignee
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.tel
     *
     * @return the value of consignee.tel
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.tel
     *
     * @param tel the value for consignee.tel
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.zipcode
     *
     * @return the value of consignee.zipcode
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.zipcode
     *
     * @param zipcode the value for consignee.zipcode
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee.default
     *
     * @return the value of consignee.default
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Boolean getDefault() {
        return default;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee.default
     *
     * @param default the value for consignee.default
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setDefault(Boolean default) {
        this.default = default;
    }
}