package com.arloor.emarket.domain;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.uname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderStatus
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.time
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Double total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oid
     *
     * @return the value of order.oid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.oid
     *
     * @param oid the value for order.oid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.uname
     *
     * @return the value of order.uname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.uname
     *
     * @param uname the value for order.uname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderStatus
     *
     * @return the value of order.orderStatus
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderStatus
     *
     * @param orderStatus the value for order.orderStatus
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.time
     *
     * @return the value of order.time
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.time
     *
     * @param time the value for order.time
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total
     *
     * @return the value of order.total
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total
     *
     * @param total the value for order.total
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setTotal(Double total) {
        this.total = total;
    }
}