package com.arloor.emarket.domain;

public class orderDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderDetail.yundan
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String yundan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderDetail.pid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderDetail.yundan
     *
     * @return the value of orderDetail.yundan
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getYundan() {
        return yundan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderDetail.yundan
     *
     * @param yundan the value for orderDetail.yundan
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setYundan(String yundan) {
        this.yundan = yundan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderDetail.pid
     *
     * @return the value of orderDetail.pid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderDetail.pid
     *
     * @param pid the value for orderDetail.pid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}