package com.arloor.emarket.domain;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.imageURL
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String imageURL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.inventory
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Integer inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.tag
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pinfo
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String pinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sellerName
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String sellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.status
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.oldPrice
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    private Double oldPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.imageURL
     *
     * @return the value of product.imageURL
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getImageURL() {
        return imageURL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.imageURL
     *
     * @param imageURL the value for product.imageURL
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.inventory
     *
     * @return the value of product.inventory
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.inventory
     *
     * @param inventory the value for product.inventory
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.tag
     *
     * @return the value of product.tag
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.tag
     *
     * @param tag the value for product.tag
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pinfo
     *
     * @return the value of product.pinfo
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getPinfo() {
        return pinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pinfo
     *
     * @param pinfo the value for product.pinfo
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setPinfo(String pinfo) {
        this.pinfo = pinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sellerName
     *
     * @return the value of product.sellerName
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sellerName
     *
     * @param sellerName the value for product.sellerName
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.oldPrice
     *
     * @return the value of product.oldPrice
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public Double getOldPrice() {
        return oldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.oldPrice
     *
     * @param oldPrice the value for product.oldPrice
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    public void setOldPrice(Double oldPrice) {
        this.oldPrice = oldPrice;
    }
}