package com.arloor.emarket.dao;

import com.arloor.emarket.domain.Cart;
import com.arloor.emarket.domain.CartKey;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int deleteByPrimaryKey(CartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    Cart selectByPrimaryKey(CartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int updateByPrimaryKey(Cart record);
}