package com.arloor.emarket.dao;

import com.arloor.emarket.domain.Consignee;
import com.arloor.emarket.domain.ConsigneeKey;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ConsigneeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int deleteByPrimaryKey(ConsigneeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int insert(Consignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int insertSelective(Consignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    Consignee selectByPrimaryKey(ConsigneeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int updateByPrimaryKeySelective(Consignee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int updateByPrimaryKey(Consignee record);
}