package com.arloor.emarket.dao;

import com.arloor.emarket.domain.Euser;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface EuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int deleteByPrimaryKey(String uname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int insert(Euser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int insertSelective(Euser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    Euser selectByPrimaryKey(String uname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int updateByPrimaryKeySelective(Euser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jun 11 11:16:20 CST 2018
     */
    int updateByPrimaryKey(Euser record);
}