package com.arloor.emarket.dao;

import com.arloor.emarket.domain.orderDetail;
import com.arloor.emarket.domain.orderDetailKey;

public interface orderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetail
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int deleteByPrimaryKey(orderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetail
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int insert(orderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetail
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int insertSelective(orderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetail
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    orderDetail selectByPrimaryKey(orderDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetail
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int updateByPrimaryKeySelective(orderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetail
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int updateByPrimaryKey(orderDetail record);
}