package com.arloor.emarket.dao;

import com.arloor.emarket.domain.ProductTag;

public interface ProductTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int insert(ProductTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int insertSelective(ProductTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    ProductTag selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int updateByPrimaryKeySelective(ProductTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Jun 11 11:02:26 CST 2018
     */
    int updateByPrimaryKey(ProductTag record);
}